# describes Postgres Database Statistics Views
# refer: https://www.postgresql.org/docs/9.6/monitoring-stats.html
name: pg_stat_activity
description: > 
         information related to the current activity 
         on a Postgres database instance D.
         This measuremnt is collected by Postgres
         statistics collector, and saved in 
         the database instance D itself.
         <p>
         This metrics fetches those statistics from
         database instance, attaches measurement
         context and time stamp and saves in a
         data warehouse for further analysis.
          
dimensions: 
      - 
        name: datid
        sql-type: oid
        description:   OID of the database on which measurement is taken
      - 
        name: datname 
        sql-type: name    
        description: Name of the database on which measurement is taken
      - 
        name: pid 
        sql-type: integer 
        description: Process ID of the database instance
        
      - 
        name: usesysid
        sql-type: oid 
        description: > 
           OID of the user logged into the database instance
      - 
        name: usename  
        sql-type: name    
        description: >
          Name of the user logged into database instance
      - 
        name: application_name
        sql-type:    text    
        description: > 
           Name of the application that is connected to this backend
      - 
        name: client_addr
        sql-type: inet 
        cast: inet   
        description: >
          IP address of the client connected to this backend. If this field is null, it indicates either that the client is connected via a Unix socket on the server machine or that this is an internal process such as autovacuum.
      - 
        name: client_hostname
        sql-type: text    
        description: >
          Host name of the connected client, as reported by a reverse DNS lookup of client_addr. This field will only be non-null for IP connections, and only when log_hostname is enabled.
      - 
        name: client_port
        sql-type: integer 
        description: > 
            TCP port number that the client is using for communication with this backend, or -1 if a Unix socket is used
      - 
         name: backend_start
         sql-type: timestamptz   
         cast: timestamptz    
         description: > 
             Time when this process was started, i.e., when the client connected to the server
      - 
        name: xact_start
        sql-type: timestamptz    
        cast: timestamptz   
        description: >
           Time when this process' current transaction was started, or null if no transaction is active. If the current query is the first of its transaction, this column is equal to the query_start column.
      - 
        name: query_start 
        sql-type: timestamptz    
        cast: timestamptz    
        description: >
           Time when the currently active query was started, or if state is not active, when the last query was started
      - 
          name: state_change
          sql-type: timestamptz    
          cast: timestamptz    
          description: > 
              Time when the state was last changed
      -
       name: wait_event_type
       sql-type: text    
       description: >
           The type of event for which the backend is waiting, if any; 
           otherwise NULL. Possible values are
           LWLockNamed The backend is waiting for a specific named lightweight lock. Each such lock protects a particular data structure in shared memory. wait_event will contain the name of the lightweight lock.

           LWLockTranche The backend is waiting for one of a group of related lightweight locks. All locks in the group perform a similar function; wait_event will identify the general purpose of locks in that group.

           Lock The backend is waiting for a heavyweight lock. Heavyweight locks, also known as lock manager locks or simply locks, primarily protect SQL-visible objects such as tables. However, they are also used to ensure mutual exclusion for certain internal operations such as relation extension. wait_event will identify the type of lock awaited.

           BufferPin The server process is waiting to access to a data buffer during a period when no other process can be examining that buffer. Buffer pin waits can be protracted if another process holds an open cursor which last read data from the buffer in question.

      - 
        name: wait_event 
        sql-type: text    
        description: >
           Wait event name if backend is currently waiting, otherwise NULL. See Table 28-4 for details.
      - 
        name: state
        sql-type: text    
        description: > 
         Current overall state of this backend. Possible values are:
         active The backend is executing a query.
         idle The backend is waiting for a new client command.
         idle in transaction The backend is in a transaction, but is not currently executing a query.
         idle in transaction (aborted) This state is similar to idle in transaction, except one of the statements in the transaction caused an error.
         fastpath function call The backend is executing a fast-path function.
         disabled This state is reported if track_activities is disabled in this backend.

      -
         name: backend_xid
         sql-type: xid 
         cast: xid
         description: >
            Top-level transaction identifier of this backend, if any.
      -
         name: backend_xmin    
         sql-type: xid 
         cast: xid
         description: > 
            The current backend's xmin horizon.
      - 
         name: query
         sql-type: text    
         description: > 
            Text of this backend's most recent query. If state is active this field shows the currently executing query. In all other states, it shows the last query that was executed.
 