# -----------------------------------------
# Configuration for Spring Boot Application
# -----------------------------------------

server: 
  servlet: 
      contextPath: /
spring: 
  application: 
     name: BPG
# directory location of catalogs w.r.t running directory
catalog: 
    database: 
      url: catalog/databases
    
database: 
    url: jdbc:postgresql://localhost:5432/bpg
    
logging: 
  level:
     com.nutanix: info
     org.springframework: error
     org.springframework.web: error

 