# -----------------------------------------
# Modular Configuration for Spring Boot Application
#
# each module is configured separtately.
#  
# -----------------------------------------
# main context path of this appliction
server: 
  servlet: 
      contextPath: /

management: 
  security: 
   enabled: "false"

security: 
  basic: 
    enabled: "false"
endpoints: 
   cors: 
     allowed-methods: GET
spring: 
  application: 
     name: BPG
     
     
logging: 
  level:
     com.nutanix:             info
     org.springframework:     error
     org.springframework.web: error
     
# each module is configured by separate yml file.
# file location is relatibe to this file
modules: 
  database: database.yml
  resource: resource.yml
  jobQueue: queues.yml  
    
    

 