# pools are enumerated by name
# for each pool, clusters are assigned by name 
# a cluster can be in multiple pool 
pools: 
  default: 
     - tomahawk 
  test: 
     - tauras
     
     
     
#     - mongoose
#  jenkins: 
#     - tauras01
#     - tomahawk4
